const STATIONS = [
  { code: 'ADM', name: 'Admiralty (NS10)' },
  { code: 'ALJ', name: 'Aljunied (EW9)' },
  { code: 'AMK', name: 'Ang Mo Kio (NS16)' },
  { code: 'CBLY', name: 'Bartley (CC12)' },
  { code: 'CBFT', name: 'BayFront (CE2)' },
  { code: 'TBSR', name: 'Bayshore (TE29)' },
  { code: 'BDK', name: 'Bedok (EW5)' },
  { code: 'CBSH', name: 'Bishan (CC15/NS17)' },
  { code: 'BNL', name: 'Boon Lay (EW27)' },
  { code: 'CBTN', name: 'Botanic Gardens (CC19)' },
  { code: 'BDL', name: 'Braddell (NS18)' },
  { code: 'CBBS', name: 'Bras Basah (CC2)' },
  { code: 'TBRH', name: 'Bright Hill (TE7)' },
  { code: 'BGS', name: 'Bugis (EW12)' },
  { code: 'BBT', name: 'Bukit Batok (NS2)' },
  { code: 'BGB', name: 'Bukit Gombak (NS3)' },
  { code: 'CBNV', name: 'Buona Vista (CC22/EW21)' },
  { code: 'TCDT', name: 'Caldecott (TE9/CC17)' },
  { code: 'CBR', name: 'Canberra (NS12)' },
  { code: 'CGA', name: 'Changi Airport (CG2)' },
  { code: 'CNG', name: 'Chinese Garden (EW25)' },
  { code: 'CCK', name: 'Choa Chu Kang (NS4)' },
  { code: 'CTH', name: 'City Hall (EW13/NS25)' },
  { code: 'CLE', name: 'Clementi (EW23)' },
  { code: 'COM', name: 'Commonwealth (EW20)' },
  { code: 'CDKT', name: 'Dakota (CC8)' },
  { code: 'CDBG', name: 'Dhoby Ghaut (CC1/NS24)' },
  { code: 'DVR', name: 'Dover (EW22)' },
  { code: 'CEPN', name: 'Esplanade (CC3)' },
  { code: 'EUN', name: 'Eunos (EW7)' },
  { code: 'XPO', name: 'Expo (CG1)' },
  { code: 'CFRR', name: 'Farrer Road (CC20)' },
  { code: 'TGRB', name: 'Gardens By The Bay (TE22)' },
  { code: 'TGRW', name: 'Great World (TE15)' },
  { code: 'GCL', name: 'GUL Circle (EW30)' },
  { code: 'CHBF', name: 'HarbourFront (CC29)' },
  { code: 'THVL', name: 'Havelock (TE16)' },
  { code: 'CHPV', name: 'Haw Par Villa (CC25)' },
  { code: 'CHLV', name: 'Holland Village (CC21)' },
  { code: 'JKN', name: 'Joo Koon (EW29)' },
  { code: 'JUR', name: 'Jurong East (EW24/NS1)' },
  { code: 'KAL', name: 'Kallang (EW10)' },
  { code: 'TKTP', name: 'Katong Park (TE24)' },
  { code: 'KEM', name: 'Kembangan (EW6)' },
  { code: 'CKRG', name: 'Kent Ridge (CC24)' },
  { code: 'KTB', name: 'Khatib (NS14)' },
  { code: 'KRJ', name: 'Kranji (NS6)' },
  { code: 'CLBD', name: 'Labrador Park (CC27)' },
  { code: 'LKS', name: 'Lakeside (EW26)' },
  { code: 'LVR', name: 'Lavender (EW11)' },
  { code: 'TLTR', name: 'Lentor (TE5)' },
  { code: 'CLRC', name: 'Lorong Chuan (CC14)' },
  { code: 'CMPS', name: 'MacPherson (CC10)' },
  { code: 'TMRB', name: 'Marina Bay (TE20/CE1/NS27)' },
  { code: 'MSP', name: 'Marina South Pier (NS28)' },
  { code: 'TMPR', name: 'Marine Parade (TE26)' },
  { code: 'TMTC', name: 'Marine Terrace (TE27)' },
  { code: 'MSL', name: 'Marsiling (NS7)' },
  { code: 'CMRM', name: 'Marymount (CC16)' },
  { code: 'TMAX', name: 'Maxwell (TE18)' },
  { code: 'TMFL', name: 'Mayflower (TE6)' },
  { code: 'CMBT', name: 'Mountbatten (CC7)' },
  { code: 'TNPR', name: 'Napier (TE12)' },
  { code: 'NEW', name: 'Newton (NS21)' },
  { code: 'CNCH', name: 'Nicoll Highway (CC5)' },
  { code: 'NOV', name: 'Novena (NS20)' },
  { code: 'CONH', name: 'One-North (CC23)' },
  { code: 'TORC', name: 'Orchard (TE14/NS22)' },
  { code: 'TOBV', name: 'Orchard Boulevard (TE13)' },
  { code: 'TOTP', name: 'Outram Park (TE17/EW16)' },
  { code: 'CPPJ', name: 'Pasir Panjang (CC26)' },
  { code: 'PSR', name: 'Pasir Ris (EW1)' },
  { code: 'CPYL', name: 'Paya Lebar (CC9/EW8)' },
  { code: 'PNR', name: 'Pioneer (EW28)' },
  { code: 'CPMN', name: 'Promenade (CC4)' },
  { code: 'QUE', name: 'Queenstown (EW19)' },
  { code: 'RFP', name: 'Raffles Place (EW14/NS26)' },
  { code: 'RDH', name: 'Redhill (EW18)' },
  { code: 'SBW', name: 'Sembawang (NS11)' },
  { code: 'CSER', name: 'Serangoon (CC13)' },
  { code: 'TSHW', name: 'Shenton Way (TE19)' },
  { code: 'TSGL', name: 'Siglap (TE28)' },
  { code: 'SIM', name: 'Simei (EW3)' },
  { code: 'SOM', name: 'Somerset (NS23)' },
  { code: 'TSPL', name: 'Springleaf (TE4)' },
  { code: 'CSDM', name: 'Stadium (CC6)' },
  { code: 'TSTV', name: 'Stevens (TE11)' },
  { code: 'CTSG', name: 'Tai Seng (CC11)' },
  { code: 'TAM', name: 'Tampines (EW2)' },
  { code: 'TNM', name: 'Tanah Merah (EW4)' },
  { code: 'TTKT', name: 'Tanjong Katong (TE25)' },
  { code: 'TPG', name: 'Tanjong Pagar (EW15)' },
  { code: 'TTRH', name: 'Tanjong Rhu (TE23)' },
  { code: 'CTLB', name: 'Telok Blangah (CC28)' },
  { code: 'TIB', name: 'Tiong Bahru (EW17)' },
  { code: 'TAP', name: 'Toa Payoh (NS19)' },
  { code: 'TCR', name: 'Tuas Crescent (EW31)' },
  { code: 'TLK', name: 'Tuas Link (EW33)' },
  { code: 'TWR', name: 'Tuas West Road (EW32)' },
  { code: 'TUTS', name: 'Upper Thomson (TE8)' },
  { code: 'TWDL', name: 'Woodlands (TE2/NS8)' },
  { code: 'TWDN', name: 'Woodlands North (TE1)' },
  { code: 'TWDS', name: 'Woodlands South (TE3)' },
  { code: 'YWT', name: 'Yew Tee (NS5)' },
  { code: 'YCK', name: 'Yio Chu Kang (NS15)' },
  { code: 'YIS', name: 'Yishun (NS13)' },
];

exports.handler = async (event) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, OPTIONS',
    'Content-Type': 'application/json',
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers, body: '' };
  }

  return {
    statusCode: 200,
    headers,
    body: JSON.stringify({
      success: true,
      data: STATIONS,
      count: STATIONS.length,
    }),
  };
};
